// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.25.0
// source: sdks/gtsportal/pb/gtsportal.proto

package pb

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGtsPortalGetToken = "/sdks.gtsportal.pb.GtsPortal/GetToken"

type GtsPortalHTTPServer interface {
	GetToken(context.Context, *GetTokenRequest) (*GetTokenReply, error)
}

func RegisterGtsPortalHTTPServer(s *http.Server, srv GtsPortalHTTPServer) {
	r := s.Route("/")
	r.POST("v1/user/profile", _GtsPortal_GetToken0_HTTP_Handler(srv))
}

func _GtsPortal_GetToken0_HTTP_Handler(srv GtsPortalHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGtsPortalGetToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetToken(ctx, req.(*GetTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTokenReply)
		return ctx.Result(200, reply)
	}
}

type GtsPortalHTTPClient interface {
	GetToken(ctx context.Context, req *GetTokenRequest, opts ...http.CallOption) (rsp *GetTokenReply, err error)
}

type GtsPortalHTTPClientImpl struct {
	cc *http.Client
}

func NewGtsPortalHTTPClient(client *http.Client) GtsPortalHTTPClient {
	return &GtsPortalHTTPClientImpl{client}
}

func (c *GtsPortalHTTPClientImpl) GetToken(ctx context.Context, in *GetTokenRequest, opts ...http.CallOption) (*GetTokenReply, error) {
	var out GetTokenReply
	pattern := "v1/user/profile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGtsPortalGetToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
