// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: sdks/gamefi_platform/pb/vo/gamefi_platform.proto

package vo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DustAddAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Action      string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Num         string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	ReferenceId string `protobuf:"bytes,4,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *DustAddAssetRequest) Reset() {
	*x = DustAddAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustAddAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustAddAssetRequest) ProtoMessage() {}

func (x *DustAddAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustAddAssetRequest.ProtoReflect.Descriptor instead.
func (*DustAddAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{0}
}

func (x *DustAddAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DustAddAssetRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DustAddAssetRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *DustAddAssetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type DustAddAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *DustAddAssetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DustAddAssetResponse) Reset() {
	*x = DustAddAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustAddAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustAddAssetResponse) ProtoMessage() {}

func (x *DustAddAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustAddAssetResponse.ProtoReflect.Descriptor instead.
func (*DustAddAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{1}
}

func (x *DustAddAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DustAddAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DustAddAssetResponse) GetData() *DustAddAssetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DustFreezeAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Action      string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Num         string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	ReferenceId string `protobuf:"bytes,4,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *DustFreezeAssetRequest) Reset() {
	*x = DustFreezeAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustFreezeAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustFreezeAssetRequest) ProtoMessage() {}

func (x *DustFreezeAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustFreezeAssetRequest.ProtoReflect.Descriptor instead.
func (*DustFreezeAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{2}
}

func (x *DustFreezeAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DustFreezeAssetRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DustFreezeAssetRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *DustFreezeAssetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type DustFreezeAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *DustFreezeAssetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DustFreezeAssetResponse) Reset() {
	*x = DustFreezeAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustFreezeAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustFreezeAssetResponse) ProtoMessage() {}

func (x *DustFreezeAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustFreezeAssetResponse.ProtoReflect.Descriptor instead.
func (*DustFreezeAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{3}
}

func (x *DustFreezeAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DustFreezeAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DustFreezeAssetResponse) GetData() *DustFreezeAssetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DustSubAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReferenceId string `protobuf:"bytes,2,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *DustSubAssetRequest) Reset() {
	*x = DustSubAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustSubAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustSubAssetRequest) ProtoMessage() {}

func (x *DustSubAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustSubAssetRequest.ProtoReflect.Descriptor instead.
func (*DustSubAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{4}
}

func (x *DustSubAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DustSubAssetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type DustSubAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    bool   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DustSubAssetResponse) Reset() {
	*x = DustSubAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustSubAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustSubAssetResponse) ProtoMessage() {}

func (x *DustSubAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustSubAssetResponse.ProtoReflect.Descriptor instead.
func (*DustSubAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{5}
}

func (x *DustSubAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DustSubAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DustSubAssetResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type DustReturnAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReferenceId string `protobuf:"bytes,2,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *DustReturnAssetRequest) Reset() {
	*x = DustReturnAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustReturnAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustReturnAssetRequest) ProtoMessage() {}

func (x *DustReturnAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustReturnAssetRequest.ProtoReflect.Descriptor instead.
func (*DustReturnAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{6}
}

func (x *DustReturnAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DustReturnAssetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type DustReturnAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *DustReturnAssetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DustReturnAssetResponse) Reset() {
	*x = DustReturnAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustReturnAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustReturnAssetResponse) ProtoMessage() {}

func (x *DustReturnAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustReturnAssetResponse.ProtoReflect.Descriptor instead.
func (*DustReturnAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{7}
}

func (x *DustReturnAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DustReturnAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DustReturnAssetResponse) GetData() *DustReturnAssetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReferenceId string                 `protobuf:"bytes,2,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	Data        []*AddHeroRequest_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AddHeroRequest) Reset() {
	*x = AddHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHeroRequest) ProtoMessage() {}

func (x *AddHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHeroRequest.ProtoReflect.Descriptor instead.
func (*AddHeroRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{8}
}

func (x *AddHeroRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddHeroRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *AddHeroRequest) GetData() []*AddHeroRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddHeroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    bool   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddHeroResponse) Reset() {
	*x = AddHeroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHeroResponse) ProtoMessage() {}

func (x *AddHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHeroResponse.ProtoReflect.Descriptor instead.
func (*AddHeroResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{9}
}

func (x *AddHeroResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddHeroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddHeroResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type FreezeHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReferenceId string   `protobuf:"bytes,2,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	UserHeroIds []string `protobuf:"bytes,3,rep,name=userHeroIds,proto3" json:"userHeroIds,omitempty"`
}

func (x *FreezeHeroRequest) Reset() {
	*x = FreezeHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreezeHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeHeroRequest) ProtoMessage() {}

func (x *FreezeHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeHeroRequest.ProtoReflect.Descriptor instead.
func (*FreezeHeroRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{10}
}

func (x *FreezeHeroRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FreezeHeroRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *FreezeHeroRequest) GetUserHeroIds() []string {
	if x != nil {
		return x.UserHeroIds
	}
	return nil
}

type FreezeHeroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    bool   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FreezeHeroResponse) Reset() {
	*x = FreezeHeroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreezeHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeHeroResponse) ProtoMessage() {}

func (x *FreezeHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeHeroResponse.ProtoReflect.Descriptor instead.
func (*FreezeHeroResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{11}
}

func (x *FreezeHeroResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FreezeHeroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FreezeHeroResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type SubHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReferenceId string `protobuf:"bytes,2,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *SubHeroRequest) Reset() {
	*x = SubHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubHeroRequest) ProtoMessage() {}

func (x *SubHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubHeroRequest.ProtoReflect.Descriptor instead.
func (*SubHeroRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{12}
}

func (x *SubHeroRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubHeroRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type SubHeroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    bool   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SubHeroResponse) Reset() {
	*x = SubHeroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubHeroResponse) ProtoMessage() {}

func (x *SubHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubHeroResponse.ProtoReflect.Descriptor instead.
func (*SubHeroResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{13}
}

func (x *SubHeroResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubHeroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubHeroResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type ReturnHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReferenceId string `protobuf:"bytes,2,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *ReturnHeroRequest) Reset() {
	*x = ReturnHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnHeroRequest) ProtoMessage() {}

func (x *ReturnHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnHeroRequest.ProtoReflect.Descriptor instead.
func (*ReturnHeroRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{14}
}

func (x *ReturnHeroRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReturnHeroRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type ReturnHeroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    bool   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReturnHeroResponse) Reset() {
	*x = ReturnHeroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnHeroResponse) ProtoMessage() {}

func (x *ReturnHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnHeroResponse.ProtoReflect.Descriptor instead.
func (*ReturnHeroResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{15}
}

func (x *ReturnHeroResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReturnHeroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReturnHeroResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type GetUserHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserHeroRequest) Reset() {
	*x = GetUserHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserHeroRequest) ProtoMessage() {}

func (x *GetUserHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserHeroRequest.ProtoReflect.Descriptor instead.
func (*GetUserHeroRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserHeroRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserHeroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *GetUserHeroResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserHeroResponse) Reset() {
	*x = GetUserHeroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserHeroResponse) ProtoMessage() {}

func (x *GetUserHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserHeroResponse.ProtoReflect.Descriptor instead.
func (*GetUserHeroResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserHeroResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserHeroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserHeroResponse) GetData() *GetUserHeroResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DustAddAssetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DustNum float32 `protobuf:"fixed32,1,opt,name=dustNum,proto3" json:"dustNum,omitempty"`
	UserId  int64   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *DustAddAssetResponse_Data) Reset() {
	*x = DustAddAssetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustAddAssetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustAddAssetResponse_Data) ProtoMessage() {}

func (x *DustAddAssetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustAddAssetResponse_Data.ProtoReflect.Descriptor instead.
func (*DustAddAssetResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DustAddAssetResponse_Data) GetDustNum() float32 {
	if x != nil {
		return x.DustNum
	}
	return 0
}

func (x *DustAddAssetResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DustFreezeAssetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DustNum float32 `protobuf:"fixed32,1,opt,name=dustNum,proto3" json:"dustNum,omitempty"`
	UserId  int64   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *DustFreezeAssetResponse_Data) Reset() {
	*x = DustFreezeAssetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustFreezeAssetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustFreezeAssetResponse_Data) ProtoMessage() {}

func (x *DustFreezeAssetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustFreezeAssetResponse_Data.ProtoReflect.Descriptor instead.
func (*DustFreezeAssetResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DustFreezeAssetResponse_Data) GetDustNum() float32 {
	if x != nil {
		return x.DustNum
	}
	return 0
}

func (x *DustFreezeAssetResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DustReturnAssetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *DustReturnAssetResponse_Data) Reset() {
	*x = DustReturnAssetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DustReturnAssetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DustReturnAssetResponse_Data) ProtoMessage() {}

func (x *DustReturnAssetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DustReturnAssetResponse_Data.ProtoReflect.Descriptor instead.
func (*DustReturnAssetResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{7, 0}
}

func (x *DustReturnAssetResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddHeroRequest_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId       string `protobuf:"bytes,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	TransferCode string `protobuf:"bytes,2,opt,name=transferCode,proto3" json:"transferCode,omitempty"`
}

func (x *AddHeroRequest_Data) Reset() {
	*x = AddHeroRequest_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHeroRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHeroRequest_Data) ProtoMessage() {}

func (x *AddHeroRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHeroRequest_Data.ProtoReflect.Descriptor instead.
func (*AddHeroRequest_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{8, 0}
}

func (x *AddHeroRequest_Data) GetHeroId() string {
	if x != nil {
		return x.HeroId
	}
	return ""
}

func (x *AddHeroRequest_Data) GetTransferCode() string {
	if x != nil {
		return x.TransferCode
	}
	return ""
}

type GetUserHeroResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId  int64 `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	UserId  int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Quality int32 `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Star    int32 `protobuf:"varint,4,opt,name=star,proto3" json:"star,omitempty"`
}

func (x *GetUserHeroResponse_Data) Reset() {
	*x = GetUserHeroResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserHeroResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserHeroResponse_Data) ProtoMessage() {}

func (x *GetUserHeroResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserHeroResponse_Data.ProtoReflect.Descriptor instead.
func (*GetUserHeroResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP(), []int{17, 0}
}

func (x *GetUserHeroResponse_Data) GetHeroId() int64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *GetUserHeroResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserHeroResponse_Data) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *GetUserHeroResponse_Data) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

var File_sdks_gamefi_platform_pb_vo_gamefi_platform_proto protoreflect.FileDescriptor

var file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDesc = []byte{
	0x0a, 0x30, 0x73, 0x64, 0x6b, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x69, 0x5f, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x6f, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x66, 0x69, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x22, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73,
	0x64, 0x6b, 0x73, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x69, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x22, 0x79, 0x0a, 0x13, 0x44, 0x75, 0x73, 0x74, 0x41, 0x64,
	0x64, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x22, 0xd1, 0x01, 0x0a, 0x14, 0x44, 0x75, 0x73, 0x74, 0x41, 0x64, 0x64, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x51, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x69, 0x5f,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x75, 0x73, 0x74,
	0x41, 0x64, 0x64, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x38, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x75, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x64, 0x75, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7c, 0x0a, 0x16, 0x44, 0x75, 0x73, 0x74, 0x46, 0x72, 0x65,
	0x65, 0x7a, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x17, 0x44, 0x75, 0x73, 0x74, 0x46, 0x72, 0x65, 0x65,
	0x7a, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x54, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x66, 0x69, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x75, 0x73, 0x74, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x38, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x75, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x64, 0x75,
	0x73, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4f, 0x0a,
	0x13, 0x44, 0x75, 0x73, 0x74, 0x53, 0x75, 0x62, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x58,
	0x0a, 0x14, 0x44, 0x75, 0x73, 0x74, 0x53, 0x75, 0x62, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x16, 0x44, 0x75, 0x73, 0x74,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0xbd, 0x01, 0x0a,
	0x17, 0x44, 0x75, 0x73, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x54, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x69, 0x5f, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x75, 0x73, 0x74, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1e, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xdb, 0x01, 0x0a,
	0x0e, 0x41, 0x64, 0x64, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x69,
	0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64,
	0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x42, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x53, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x6f, 0x0a, 0x11, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x73,
	0x22, 0x56, 0x0a, 0x12, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x48,
	0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x48, 0x65, 0x72, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4d, 0x0a, 0x11, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xfb, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x50, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x66, 0x69, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x64,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x74, 0x61, 0x72, 0x42, 0x2a, 0x5a, 0x28, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x73, 0x64, 0x6b, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x69, 0x5f, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x6f, 0x3b, 0x76, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescOnce sync.Once
	file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescData = file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDesc
)

func file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescGZIP() []byte {
	file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescOnce.Do(func() {
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescData)
	})
	return file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDescData
}

var file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_goTypes = []interface{}{
	(*DustAddAssetRequest)(nil),          // 0: components.sdks.gamefi_platform.pb.DustAddAssetRequest
	(*DustAddAssetResponse)(nil),         // 1: components.sdks.gamefi_platform.pb.DustAddAssetResponse
	(*DustFreezeAssetRequest)(nil),       // 2: components.sdks.gamefi_platform.pb.DustFreezeAssetRequest
	(*DustFreezeAssetResponse)(nil),      // 3: components.sdks.gamefi_platform.pb.DustFreezeAssetResponse
	(*DustSubAssetRequest)(nil),          // 4: components.sdks.gamefi_platform.pb.DustSubAssetRequest
	(*DustSubAssetResponse)(nil),         // 5: components.sdks.gamefi_platform.pb.DustSubAssetResponse
	(*DustReturnAssetRequest)(nil),       // 6: components.sdks.gamefi_platform.pb.DustReturnAssetRequest
	(*DustReturnAssetResponse)(nil),      // 7: components.sdks.gamefi_platform.pb.DustReturnAssetResponse
	(*AddHeroRequest)(nil),               // 8: components.sdks.gamefi_platform.pb.AddHeroRequest
	(*AddHeroResponse)(nil),              // 9: components.sdks.gamefi_platform.pb.AddHeroResponse
	(*FreezeHeroRequest)(nil),            // 10: components.sdks.gamefi_platform.pb.FreezeHeroRequest
	(*FreezeHeroResponse)(nil),           // 11: components.sdks.gamefi_platform.pb.FreezeHeroResponse
	(*SubHeroRequest)(nil),               // 12: components.sdks.gamefi_platform.pb.SubHeroRequest
	(*SubHeroResponse)(nil),              // 13: components.sdks.gamefi_platform.pb.SubHeroResponse
	(*ReturnHeroRequest)(nil),            // 14: components.sdks.gamefi_platform.pb.ReturnHeroRequest
	(*ReturnHeroResponse)(nil),           // 15: components.sdks.gamefi_platform.pb.ReturnHeroResponse
	(*GetUserHeroRequest)(nil),           // 16: components.sdks.gamefi_platform.pb.GetUserHeroRequest
	(*GetUserHeroResponse)(nil),          // 17: components.sdks.gamefi_platform.pb.GetUserHeroResponse
	(*DustAddAssetResponse_Data)(nil),    // 18: components.sdks.gamefi_platform.pb.DustAddAssetResponse.Data
	(*DustFreezeAssetResponse_Data)(nil), // 19: components.sdks.gamefi_platform.pb.DustFreezeAssetResponse.Data
	(*DustReturnAssetResponse_Data)(nil), // 20: components.sdks.gamefi_platform.pb.DustReturnAssetResponse.Data
	(*AddHeroRequest_Data)(nil),          // 21: components.sdks.gamefi_platform.pb.AddHeroRequest.Data
	(*GetUserHeroResponse_Data)(nil),     // 22: components.sdks.gamefi_platform.pb.GetUserHeroResponse.Data
}
var file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_depIdxs = []int32{
	18, // 0: components.sdks.gamefi_platform.pb.DustAddAssetResponse.data:type_name -> components.sdks.gamefi_platform.pb.DustAddAssetResponse.Data
	19, // 1: components.sdks.gamefi_platform.pb.DustFreezeAssetResponse.data:type_name -> components.sdks.gamefi_platform.pb.DustFreezeAssetResponse.Data
	20, // 2: components.sdks.gamefi_platform.pb.DustReturnAssetResponse.data:type_name -> components.sdks.gamefi_platform.pb.DustReturnAssetResponse.Data
	21, // 3: components.sdks.gamefi_platform.pb.AddHeroRequest.data:type_name -> components.sdks.gamefi_platform.pb.AddHeroRequest.Data
	22, // 4: components.sdks.gamefi_platform.pb.GetUserHeroResponse.data:type_name -> components.sdks.gamefi_platform.pb.GetUserHeroResponse.Data
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_init() }
func file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_init() {
	if File_sdks_gamefi_platform_pb_vo_gamefi_platform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustAddAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustAddAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustFreezeAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustFreezeAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustSubAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustSubAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustReturnAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustReturnAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHeroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreezeHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreezeHeroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubHeroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnHeroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserHeroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustAddAssetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustFreezeAssetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DustReturnAssetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHeroRequest_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserHeroResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_goTypes,
		DependencyIndexes: file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_depIdxs,
		MessageInfos:      file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_msgTypes,
	}.Build()
	File_sdks_gamefi_platform_pb_vo_gamefi_platform_proto = out.File
	file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_rawDesc = nil
	file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_goTypes = nil
	file_sdks_gamefi_platform_pb_vo_gamefi_platform_proto_depIdxs = nil
}
