// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: common/proto/http.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK Code = 0
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "OK",
	}
	Code_value = map[string]int32{
		"OK": 0,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_http_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_common_proto_http_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_http_proto_rawDescGZIP(), []int{0}
}

// 自定义错误体,用于global.http.EncoderError函数
type ErrorWithDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorWithDetails) Reset() {
	*x = ErrorWithDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorWithDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorWithDetails) ProtoMessage() {}

func (x *ErrorWithDetails) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorWithDetails.ProtoReflect.Descriptor instead.
func (*ErrorWithDetails) Descriptor() ([]byte, []int) {
	return file_common_proto_http_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorWithDetails) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorWithDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto_http_proto protoreflect.FileDescriptor

var file_common_proto_http_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22,
	0x40, 0x0a, 0x10, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2a, 0x0e, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x42, 0x28, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1d, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_common_proto_http_proto_rawDescOnce sync.Once
	file_common_proto_http_proto_rawDescData = file_common_proto_http_proto_rawDesc
)

func file_common_proto_http_proto_rawDescGZIP() []byte {
	file_common_proto_http_proto_rawDescOnce.Do(func() {
		file_common_proto_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_http_proto_rawDescData)
	})
	return file_common_proto_http_proto_rawDescData
}

var file_common_proto_http_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_http_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_http_proto_goTypes = []interface{}{
	(Code)(0),                // 0: game.Code
	(*ErrorWithDetails)(nil), // 1: game.ErrorWithDetails
}
var file_common_proto_http_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_http_proto_init() }
func file_common_proto_http_proto_init() {
	if File_common_proto_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorWithDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_http_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_http_proto_goTypes,
		DependencyIndexes: file_common_proto_http_proto_depIdxs,
		EnumInfos:         file_common_proto_http_proto_enumTypes,
		MessageInfos:      file_common_proto_http_proto_msgTypes,
	}.Build()
	File_common_proto_http_proto = out.File
	file_common_proto_http_proto_rawDesc = nil
	file_common_proto_http_proto_goTypes = nil
	file_common_proto_http_proto_depIdxs = nil
}
