// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: sdks/gts_shop/pb/vo/gts_shop.proto

package vo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AuthorizationCodeRequest) Reset() {
	*x = AuthorizationCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCodeRequest) ProtoMessage() {}

func (x *AuthorizationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCodeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationCodeRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// email和phone
type SendVerificationCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *SendVerificationCodeRequest) Reset() {
	*x = SendVerificationCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeRequest) ProtoMessage() {}

func (x *SendVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{1}
}

func (x *SendVerificationCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SendVerificationCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *SendVerificationCodeResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendVerificationCodeResponse) Reset() {
	*x = SendVerificationCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendVerificationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeResponse) ProtoMessage() {}

func (x *SendVerificationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeResponse.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{2}
}

func (x *SendVerificationCodeResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendVerificationCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendVerificationCodeResponse) GetData() *SendVerificationCodeResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type VerifyCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`         // 用户ID
	GoogleCode string `protobuf:"bytes,2,opt,name=googleCode,proto3" json:"googleCode,omitempty"` // 验证码
}

func (x *VerifyCodeRequest) Reset() {
	*x = VerifyCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRequest) ProtoMessage() {}

func (x *VerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyCodeRequest) GetGoogleCode() string {
	if x != nil {
		return x.GoogleCode
	}
	return ""
}

type VerifyCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    bool   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *VerifyCodeResponse) Reset() {
	*x = VerifyCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeResponse) ProtoMessage() {}

func (x *VerifyCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyCodeResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyCodeResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifyCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyCodeResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type UserProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenUserId string `protobuf:"bytes,1,opt,name=tokenUserId,proto3" json:"tokenUserId,omitempty"`
}

func (x *UserProfileRequest) Reset() {
	*x = UserProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileRequest) ProtoMessage() {}

func (x *UserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileRequest.ProtoReflect.Descriptor instead.
func (*UserProfileRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{5}
}

func (x *UserProfileRequest) GetTokenUserId() string {
	if x != nil {
		return x.TokenUserId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *GetAccountResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAccountResponse) GetData() *GetAccountResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealUserId string `protobuf:"bytes,1,opt,name=realUserId,proto3" json:"realUserId,omitempty"`
}

func (x *ListAssetRequest) Reset() {
	*x = ListAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetRequest) ProtoMessage() {}

func (x *ListAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetRequest.ProtoReflect.Descriptor instead.
func (*ListAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{7}
}

func (x *ListAssetRequest) GetRealUserId() string {
	if x != nil {
		return x.RealUserId
	}
	return ""
}

type ListAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *ListAssetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ListAssetResponse) Reset() {
	*x = ListAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetResponse) ProtoMessage() {}

func (x *ListAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetResponse.ProtoReflect.Descriptor instead.
func (*ListAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{8}
}

func (x *ListAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListAssetResponse) GetData() *ListAssetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Action      string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Num         string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	ReferenceId string `protobuf:"bytes,4,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *AddAssetRequest) Reset() {
	*x = AddAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssetRequest) ProtoMessage() {}

func (x *AddAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssetRequest.ProtoReflect.Descriptor instead.
func (*AddAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{9}
}

func (x *AddAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddAssetRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AddAssetRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *AddAssetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type AddAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *AddAssetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddAssetResponse) Reset() {
	*x = AddAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssetResponse) ProtoMessage() {}

func (x *AddAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssetResponse.ProtoReflect.Descriptor instead.
func (*AddAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{10}
}

func (x *AddAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddAssetResponse) GetData() *AddAssetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type FreezeAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Action      string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Num         string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	ReferenceId string `protobuf:"bytes,4,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *FreezeAssetRequest) Reset() {
	*x = FreezeAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreezeAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeAssetRequest) ProtoMessage() {}

func (x *FreezeAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeAssetRequest.ProtoReflect.Descriptor instead.
func (*FreezeAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{11}
}

func (x *FreezeAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FreezeAssetRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FreezeAssetRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *FreezeAssetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type FreezeAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *FreezeAssetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FreezeAssetResponse) Reset() {
	*x = FreezeAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreezeAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeAssetResponse) ProtoMessage() {}

func (x *FreezeAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeAssetResponse.ProtoReflect.Descriptor instead.
func (*FreezeAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{12}
}

func (x *FreezeAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FreezeAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FreezeAssetResponse) GetData() *FreezeAssetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Action      string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Num         string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	ReferenceId string `protobuf:"bytes,4,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *SubAssetRequest) Reset() {
	*x = SubAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAssetRequest) ProtoMessage() {}

func (x *SubAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAssetRequest.ProtoReflect.Descriptor instead.
func (*SubAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{13}
}

func (x *SubAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubAssetRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SubAssetRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *SubAssetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type SubAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *SubAssetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SubAssetResponse) Reset() {
	*x = SubAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAssetResponse) ProtoMessage() {}

func (x *SubAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAssetResponse.ProtoReflect.Descriptor instead.
func (*SubAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{14}
}

func (x *SubAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubAssetResponse) GetData() *SubAssetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReturnAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Action      string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Num         string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	ReferenceId string `protobuf:"bytes,4,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
}

func (x *ReturnAssetRequest) Reset() {
	*x = ReturnAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAssetRequest) ProtoMessage() {}

func (x *ReturnAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAssetRequest.ProtoReflect.Descriptor instead.
func (*ReturnAssetRequest) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{15}
}

func (x *ReturnAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReturnAssetRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ReturnAssetRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *ReturnAssetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type ReturnAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *ReturnAssetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReturnAssetResponse) Reset() {
	*x = ReturnAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAssetResponse) ProtoMessage() {}

func (x *ReturnAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAssetResponse.ProtoReflect.Descriptor instead.
func (*ReturnAssetResponse) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{16}
}

func (x *ReturnAssetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReturnAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReturnAssetResponse) GetData() *ReturnAssetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendVerificationCodeResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` //mail or phone
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SendVerificationCodeResponse_Data) Reset() {
	*x = SendVerificationCodeResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendVerificationCodeResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeResponse_Data) ProtoMessage() {}

func (x *SendVerificationCodeResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeResponse_Data.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SendVerificationCodeResponse_Data) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SendVerificationCodeResponse_Data) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetAccountResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealUserId  string `protobuf:"bytes,1,opt,name=realUserId,proto3" json:"realUserId,omitempty"`
	TokenUserId string `protobuf:"bytes,2,opt,name=tokenUserId,proto3" json:"tokenUserId,omitempty"`
	NickName    string `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Avatar      string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	BindEmail   bool   `protobuf:"varint,5,opt,name=bindEmail,proto3" json:"bindEmail,omitempty"`
	BindPhone   bool   `protobuf:"varint,6,opt,name=bindPhone,proto3" json:"bindPhone,omitempty"`
	BindGA      bool   `protobuf:"varint,7,opt,name=bindGA,proto3" json:"bindGA,omitempty"`
}

func (x *GetAccountResponse_Data) Reset() {
	*x = GetAccountResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse_Data) ProtoMessage() {}

func (x *GetAccountResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse_Data.ProtoReflect.Descriptor instead.
func (*GetAccountResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetAccountResponse_Data) GetRealUserId() string {
	if x != nil {
		return x.RealUserId
	}
	return ""
}

func (x *GetAccountResponse_Data) GetTokenUserId() string {
	if x != nil {
		return x.TokenUserId
	}
	return ""
}

func (x *GetAccountResponse_Data) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *GetAccountResponse_Data) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetAccountResponse_Data) GetBindEmail() bool {
	if x != nil {
		return x.BindEmail
	}
	return false
}

func (x *GetAccountResponse_Data) GetBindPhone() bool {
	if x != nil {
		return x.BindPhone
	}
	return false
}

func (x *GetAccountResponse_Data) GetBindGA() bool {
	if x != nil {
		return x.BindGA
	}
	return false
}

type ListAssetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserGalaxyDust *ListAssetResponse_Data_UserGalaxyDust `protobuf:"bytes,1,opt,name=userGalaxyDust,proto3" json:"userGalaxyDust,omitempty"`
	UserGp         *ListAssetResponse_Data_UserGp         `protobuf:"bytes,2,opt,name=userGp,proto3" json:"userGp,omitempty"`
}

func (x *ListAssetResponse_Data) Reset() {
	*x = ListAssetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetResponse_Data) ProtoMessage() {}

func (x *ListAssetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetResponse_Data.ProtoReflect.Descriptor instead.
func (*ListAssetResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ListAssetResponse_Data) GetUserGalaxyDust() *ListAssetResponse_Data_UserGalaxyDust {
	if x != nil {
		return x.UserGalaxyDust
	}
	return nil
}

func (x *ListAssetResponse_Data) GetUserGp() *ListAssetResponse_Data_UserGp {
	if x != nil {
		return x.UserGp
	}
	return nil
}

type ListAssetResponse_Data_UserGalaxyDust struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DustNum float32 `protobuf:"fixed32,1,opt,name=dustNum,proto3" json:"dustNum,omitempty"`
	UserId  int64   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ListAssetResponse_Data_UserGalaxyDust) Reset() {
	*x = ListAssetResponse_Data_UserGalaxyDust{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssetResponse_Data_UserGalaxyDust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetResponse_Data_UserGalaxyDust) ProtoMessage() {}

func (x *ListAssetResponse_Data_UserGalaxyDust) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetResponse_Data_UserGalaxyDust.ProtoReflect.Descriptor instead.
func (*ListAssetResponse_Data_UserGalaxyDust) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{8, 0, 0}
}

func (x *ListAssetResponse_Data_UserGalaxyDust) GetDustNum() float32 {
	if x != nil {
		return x.DustNum
	}
	return 0
}

func (x *ListAssetResponse_Data_UserGalaxyDust) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListAssetResponse_Data_UserGp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GpValue float32 `protobuf:"fixed32,1,opt,name=gpValue,proto3" json:"gpValue,omitempty"`
	UserId  int64   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ListAssetResponse_Data_UserGp) Reset() {
	*x = ListAssetResponse_Data_UserGp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssetResponse_Data_UserGp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetResponse_Data_UserGp) ProtoMessage() {}

func (x *ListAssetResponse_Data_UserGp) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetResponse_Data_UserGp.ProtoReflect.Descriptor instead.
func (*ListAssetResponse_Data_UserGp) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{8, 0, 1}
}

func (x *ListAssetResponse_Data_UserGp) GetGpValue() float32 {
	if x != nil {
		return x.GpValue
	}
	return 0
}

func (x *ListAssetResponse_Data_UserGp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddAssetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *AddAssetResponse_Data) Reset() {
	*x = AddAssetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAssetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssetResponse_Data) ProtoMessage() {}

func (x *AddAssetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssetResponse_Data.ProtoReflect.Descriptor instead.
func (*AddAssetResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{10, 0}
}

func (x *AddAssetResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FreezeAssetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *FreezeAssetResponse_Data) Reset() {
	*x = FreezeAssetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreezeAssetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeAssetResponse_Data) ProtoMessage() {}

func (x *FreezeAssetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeAssetResponse_Data.ProtoReflect.Descriptor instead.
func (*FreezeAssetResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{12, 0}
}

func (x *FreezeAssetResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SubAssetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *SubAssetResponse_Data) Reset() {
	*x = SubAssetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubAssetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAssetResponse_Data) ProtoMessage() {}

func (x *SubAssetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAssetResponse_Data.ProtoReflect.Descriptor instead.
func (*SubAssetResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{14, 0}
}

func (x *SubAssetResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReturnAssetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ReturnAssetResponse_Data) Reset() {
	*x = ReturnAssetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnAssetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAssetResponse_Data) ProtoMessage() {}

func (x *ReturnAssetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAssetResponse_Data.ProtoReflect.Descriptor instead.
func (*ReturnAssetResponse_Data) Descriptor() ([]byte, []int) {
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP(), []int{16, 0}
}

func (x *ReturnAssetResponse_Data) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_sdks_gts_shop_pb_vo_gts_shop_proto protoreflect.FileDescriptor

var file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x64, 0x6b, 0x73, 0x2f, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2f,
	0x70, 0x62, 0x2f, 0x76, 0x6f, 0x2f, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70,
	0x62, 0x22, 0x2e, 0x0a, 0x18, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x35, 0x0a, 0x1b, 0x53, 0x65, 0x6e, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xd0, 0x01, 0x0a, 0x1c, 0x53, 0x65, 0x6e,
	0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x52, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2e, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x56, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x36, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xdf, 0x02, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x48, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x74,
	0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xd0, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x64, 0x47, 0x41, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x64, 0x47, 0x41, 0x22, 0x32, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xd3,
	0x03, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x47, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x33, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64,
	0x6b, 0x73, 0x2e, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xc6, 0x02, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x6a, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x47, 0x61, 0x6c, 0x61,
	0x78, 0x79, 0x44, 0x75, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67,
	0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x44, 0x75, 0x73, 0x74,
	0x52, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x47, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x44, 0x75, 0x73, 0x74,
	0x12, 0x52, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x47, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64,
	0x6b, 0x73, 0x2e, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x70, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x47, 0x70, 0x1a, 0x42, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x6c, 0x61,
	0x78, 0x79, 0x44, 0x75, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x75, 0x73, 0x74, 0x4e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x64, 0x75, 0x73, 0x74, 0x4e, 0x75, 0x6d,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x3a, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x67, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x10,
	0x41, 0x64, 0x64, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x46,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67,
	0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x12, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x22, 0xae, 0x01, 0x0a, 0x13, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x49, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x1e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x75, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x10, 0x53, 0x75, 0x62,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x46, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73, 0x64, 0x6b, 0x73, 0x2e, 0x67, 0x74, 0x73, 0x5f,
	0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x62, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x1e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0xae, 0x01,
	0x0a, 0x13, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x49, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x73,
	0x64, 0x6b, 0x73, 0x2e, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1e,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x23,
	0x5a, 0x21, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x73, 0x64, 0x6b,
	0x73, 0x2f, 0x67, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x6f,
	0x3b, 0x76, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescOnce sync.Once
	file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescData = file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDesc
)

func file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescGZIP() []byte {
	file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescOnce.Do(func() {
		file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescData)
	})
	return file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDescData
}

var file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_sdks_gts_shop_pb_vo_gts_shop_proto_goTypes = []interface{}{
	(*AuthorizationCodeRequest)(nil),              // 0: components.sdks.gts_shop.pb.AuthorizationCodeRequest
	(*SendVerificationCodeRequest)(nil),           // 1: components.sdks.gts_shop.pb.SendVerificationCodeRequest
	(*SendVerificationCodeResponse)(nil),          // 2: components.sdks.gts_shop.pb.SendVerificationCodeResponse
	(*VerifyCodeRequest)(nil),                     // 3: components.sdks.gts_shop.pb.VerifyCodeRequest
	(*VerifyCodeResponse)(nil),                    // 4: components.sdks.gts_shop.pb.VerifyCodeResponse
	(*UserProfileRequest)(nil),                    // 5: components.sdks.gts_shop.pb.UserProfileRequest
	(*GetAccountResponse)(nil),                    // 6: components.sdks.gts_shop.pb.GetAccountResponse
	(*ListAssetRequest)(nil),                      // 7: components.sdks.gts_shop.pb.ListAssetRequest
	(*ListAssetResponse)(nil),                     // 8: components.sdks.gts_shop.pb.ListAssetResponse
	(*AddAssetRequest)(nil),                       // 9: components.sdks.gts_shop.pb.AddAssetRequest
	(*AddAssetResponse)(nil),                      // 10: components.sdks.gts_shop.pb.AddAssetResponse
	(*FreezeAssetRequest)(nil),                    // 11: components.sdks.gts_shop.pb.FreezeAssetRequest
	(*FreezeAssetResponse)(nil),                   // 12: components.sdks.gts_shop.pb.FreezeAssetResponse
	(*SubAssetRequest)(nil),                       // 13: components.sdks.gts_shop.pb.SubAssetRequest
	(*SubAssetResponse)(nil),                      // 14: components.sdks.gts_shop.pb.SubAssetResponse
	(*ReturnAssetRequest)(nil),                    // 15: components.sdks.gts_shop.pb.ReturnAssetRequest
	(*ReturnAssetResponse)(nil),                   // 16: components.sdks.gts_shop.pb.ReturnAssetResponse
	(*SendVerificationCodeResponse_Data)(nil),     // 17: components.sdks.gts_shop.pb.SendVerificationCodeResponse.Data
	(*GetAccountResponse_Data)(nil),               // 18: components.sdks.gts_shop.pb.GetAccountResponse.Data
	(*ListAssetResponse_Data)(nil),                // 19: components.sdks.gts_shop.pb.ListAssetResponse.Data
	(*ListAssetResponse_Data_UserGalaxyDust)(nil), // 20: components.sdks.gts_shop.pb.ListAssetResponse.Data.UserGalaxyDust
	(*ListAssetResponse_Data_UserGp)(nil),         // 21: components.sdks.gts_shop.pb.ListAssetResponse.Data.UserGp
	(*AddAssetResponse_Data)(nil),                 // 22: components.sdks.gts_shop.pb.AddAssetResponse.Data
	(*FreezeAssetResponse_Data)(nil),              // 23: components.sdks.gts_shop.pb.FreezeAssetResponse.Data
	(*SubAssetResponse_Data)(nil),                 // 24: components.sdks.gts_shop.pb.SubAssetResponse.Data
	(*ReturnAssetResponse_Data)(nil),              // 25: components.sdks.gts_shop.pb.ReturnAssetResponse.Data
}
var file_sdks_gts_shop_pb_vo_gts_shop_proto_depIdxs = []int32{
	17, // 0: components.sdks.gts_shop.pb.SendVerificationCodeResponse.data:type_name -> components.sdks.gts_shop.pb.SendVerificationCodeResponse.Data
	18, // 1: components.sdks.gts_shop.pb.GetAccountResponse.data:type_name -> components.sdks.gts_shop.pb.GetAccountResponse.Data
	19, // 2: components.sdks.gts_shop.pb.ListAssetResponse.data:type_name -> components.sdks.gts_shop.pb.ListAssetResponse.Data
	22, // 3: components.sdks.gts_shop.pb.AddAssetResponse.data:type_name -> components.sdks.gts_shop.pb.AddAssetResponse.Data
	23, // 4: components.sdks.gts_shop.pb.FreezeAssetResponse.data:type_name -> components.sdks.gts_shop.pb.FreezeAssetResponse.Data
	24, // 5: components.sdks.gts_shop.pb.SubAssetResponse.data:type_name -> components.sdks.gts_shop.pb.SubAssetResponse.Data
	25, // 6: components.sdks.gts_shop.pb.ReturnAssetResponse.data:type_name -> components.sdks.gts_shop.pb.ReturnAssetResponse.Data
	20, // 7: components.sdks.gts_shop.pb.ListAssetResponse.Data.userGalaxyDust:type_name -> components.sdks.gts_shop.pb.ListAssetResponse.Data.UserGalaxyDust
	21, // 8: components.sdks.gts_shop.pb.ListAssetResponse.Data.userGp:type_name -> components.sdks.gts_shop.pb.ListAssetResponse.Data.UserGp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_sdks_gts_shop_pb_vo_gts_shop_proto_init() }
func file_sdks_gts_shop_pb_vo_gts_shop_proto_init() {
	if File_sdks_gts_shop_pb_vo_gts_shop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendVerificationCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendVerificationCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreezeAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreezeAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendVerificationCodeResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssetResponse_Data_UserGalaxyDust); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssetResponse_Data_UserGp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAssetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreezeAssetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubAssetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnAssetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdks_gts_shop_pb_vo_gts_shop_proto_goTypes,
		DependencyIndexes: file_sdks_gts_shop_pb_vo_gts_shop_proto_depIdxs,
		MessageInfos:      file_sdks_gts_shop_pb_vo_gts_shop_proto_msgTypes,
	}.Build()
	File_sdks_gts_shop_pb_vo_gts_shop_proto = out.File
	file_sdks_gts_shop_pb_vo_gts_shop_proto_rawDesc = nil
	file_sdks_gts_shop_pb_vo_gts_shop_proto_goTypes = nil
	file_sdks_gts_shop_pb_vo_gts_shop_proto_depIdxs = nil
}
