// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: sdks/gamefi_account/pb/gamefi_account.proto

package pb

import (
	vo "components/sdks/gamefi_account/pb/vo"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GamefiAccount_SendEmail_FullMethodName = "/components.sdks.gamefi_account.pb.GamefiAccount/SendEmail"
)

// GamefiAccountClient is the client API for GamefiAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GamefiAccountClient interface {
	// 发送邮件
	SendEmail(ctx context.Context, in *vo.SendEmailRequest, opts ...grpc.CallOption) (*vo.SendEmailResponse, error)
}

type gamefiAccountClient struct {
	cc grpc.ClientConnInterface
}

func NewGamefiAccountClient(cc grpc.ClientConnInterface) GamefiAccountClient {
	return &gamefiAccountClient{cc}
}

func (c *gamefiAccountClient) SendEmail(ctx context.Context, in *vo.SendEmailRequest, opts ...grpc.CallOption) (*vo.SendEmailResponse, error) {
	out := new(vo.SendEmailResponse)
	err := c.cc.Invoke(ctx, GamefiAccount_SendEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GamefiAccountServer is the server API for GamefiAccount service.
// All implementations must embed UnimplementedGamefiAccountServer
// for forward compatibility
type GamefiAccountServer interface {
	// 发送邮件
	SendEmail(context.Context, *vo.SendEmailRequest) (*vo.SendEmailResponse, error)
	mustEmbedUnimplementedGamefiAccountServer()
}

// UnimplementedGamefiAccountServer must be embedded to have forward compatible implementations.
type UnimplementedGamefiAccountServer struct {
}

func (UnimplementedGamefiAccountServer) SendEmail(context.Context, *vo.SendEmailRequest) (*vo.SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedGamefiAccountServer) mustEmbedUnimplementedGamefiAccountServer() {}

// UnsafeGamefiAccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GamefiAccountServer will
// result in compilation errors.
type UnsafeGamefiAccountServer interface {
	mustEmbedUnimplementedGamefiAccountServer()
}

func RegisterGamefiAccountServer(s grpc.ServiceRegistrar, srv GamefiAccountServer) {
	s.RegisterService(&GamefiAccount_ServiceDesc, srv)
}

func _GamefiAccount_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vo.SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamefiAccountServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamefiAccount_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamefiAccountServer).SendEmail(ctx, req.(*vo.SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GamefiAccount_ServiceDesc is the grpc.ServiceDesc for GamefiAccount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GamefiAccount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "components.sdks.gamefi_account.pb.GamefiAccount",
	HandlerType: (*GamefiAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _GamefiAccount_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdks/gamefi_account/pb/gamefi_account.proto",
}
