nacos:
  group: gamefi
  ip: 127.0.0.1
  port: 8848
  userName: "nacos"
  pwd: "nacos"
  namespaceId: 72984690-125b-436d-83ba-b201d4f9e6a0
  timeoutMs: 5000
log:
  name: gamefi_equipment
  dir: /Users/iworkspace/ifarm_golang/gamefi_equipment
  debug: true
server:
  http:
    addr: 0.0.0.0:8010
    timeout: 60s
  grpc:
    addr: 0.0.0.0:8011
    timeout: 60s
data:
  postgres:
    source: postgresql://gametacus_user:123456@10.40.10.3:5432/gamefi_platform?sslmode=disable
    debug: true
    pool_size: 20
    read_timeout: 5s
    write_timeout: 5s
    idle: 10
    idle_timeout: 10s
  redis:
    addr: 10.40.10.15:6379
    auth: game123456
    dial_timeout: 1s
    read_timeout: 1s
    write_timeout: 1s
    active: 20
    idle: 10
    idle_timeout: 10s
    slow_log: 1s
kafka:
  logevent:
    topic: qa_equipment_log_event
    addr: 10.40.10.2:9092
client:
  platform_dust:
    endpoint: http://10.40.10.10:30005
    timeout: 10s
  gamefi_account:
    endpoint: http://10.40.10.10:30006
    timeout: 10s
sys:
  config_path: /Users/iworkspace/ifarm_golang/gamefi_config