// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: api/in/v1/vo/equipment.proto

package vo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EquipmentStatus int32

const (
	EquipmentStatus_None      EquipmentStatus = 0
	EquipmentStatus_Normal    EquipmentStatus = 1 //未使用
	EquipmentStatus_Equipped  EquipmentStatus = 2 //已穿戴
	EquipmentStatus_Locked    EquipmentStatus = 3 //已锁定
	EquipmentStatus_Withdrawn EquipmentStatus = 4 //已提现
	EquipmentStatus_BreakDown EquipmentStatus = 5 //已分解
)

// Enum value maps for EquipmentStatus.
var (
	EquipmentStatus_name = map[int32]string{
		0: "None",
		1: "Normal",
		2: "Equipped",
		3: "Locked",
		4: "Withdrawn",
		5: "BreakDown",
	}
	EquipmentStatus_value = map[string]int32{
		"None":      0,
		"Normal":    1,
		"Equipped":  2,
		"Locked":    3,
		"Withdrawn": 4,
		"BreakDown": 5,
	}
)

func (x EquipmentStatus) Enum() *EquipmentStatus {
	p := new(EquipmentStatus)
	*p = x
	return p
}

func (x EquipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EquipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_in_v1_vo_equipment_proto_enumTypes[0].Descriptor()
}

func (EquipmentStatus) Type() protoreflect.EnumType {
	return &file_api_in_v1_vo_equipment_proto_enumTypes[0]
}

func (x EquipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EquipmentStatus.Descriptor instead.
func (EquipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{0}
}

type HeroEquipment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserHeroId int64            `protobuf:"varint,1,opt,name=userHeroId,proto3" json:"userHeroId,omitempty"`
	Equipments []*EquipmentInfo `protobuf:"bytes,2,rep,name=equipments,proto3" json:"equipments,omitempty"`
	TotalAttr  []*Attr          `protobuf:"bytes,3,rep,name=totalAttr,proto3" json:"totalAttr,omitempty"`
}

func (x *HeroEquipment) Reset() {
	*x = HeroEquipment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroEquipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroEquipment) ProtoMessage() {}

func (x *HeroEquipment) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroEquipment.ProtoReflect.Descriptor instead.
func (*HeroEquipment) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{0}
}

func (x *HeroEquipment) GetUserHeroId() int64 {
	if x != nil {
		return x.UserHeroId
	}
	return 0
}

func (x *HeroEquipment) GetEquipments() []*EquipmentInfo {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *HeroEquipment) GetTotalAttr() []*Attr {
	if x != nil {
		return x.TotalAttr
	}
	return nil
}

type EquipmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseId       int64           `protobuf:"varint,2,opt,name=baseId,proto3" json:"baseId,omitempty"`
	UserId       int64           `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	HeroId       int64           `protobuf:"varint,4,opt,name=heroId,proto3" json:"heroId,omitempty"`
	UserHeroId   int64           `protobuf:"varint,5,opt,name=userHeroId,proto3" json:"userHeroId,omitempty"`
	Level        int32           `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Star         int32           `protobuf:"varint,7,opt,name=star,proto3" json:"star,omitempty"`
	Status       EquipmentStatus `protobuf:"varint,8,opt,name=status,proto3,enum=api.in.v1.EquipmentStatus" json:"status,omitempty"`
	InitAttrs    []*Attr         `protobuf:"bytes,9,rep,name=initAttrs,proto3" json:"initAttrs,omitempty"`        // 初始属性
	UpgradeAttrs []*Attr         `protobuf:"bytes,10,rep,name=upgradeAttrs,proto3" json:"upgradeAttrs,omitempty"` // 强化属性
	Position     int32           `protobuf:"varint,11,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *EquipmentInfo) Reset() {
	*x = EquipmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentInfo) ProtoMessage() {}

func (x *EquipmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentInfo.ProtoReflect.Descriptor instead.
func (*EquipmentInfo) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{1}
}

func (x *EquipmentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipmentInfo) GetBaseId() int64 {
	if x != nil {
		return x.BaseId
	}
	return 0
}

func (x *EquipmentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EquipmentInfo) GetHeroId() int64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *EquipmentInfo) GetUserHeroId() int64 {
	if x != nil {
		return x.UserHeroId
	}
	return 0
}

func (x *EquipmentInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EquipmentInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *EquipmentInfo) GetStatus() EquipmentStatus {
	if x != nil {
		return x.Status
	}
	return EquipmentStatus_None
}

func (x *EquipmentInfo) GetInitAttrs() []*Attr {
	if x != nil {
		return x.InitAttrs
	}
	return nil
}

func (x *EquipmentInfo) GetUpgradeAttrs() []*Attr {
	if x != nil {
		return x.UpgradeAttrs
	}
	return nil
}

func (x *EquipmentInfo) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type Attr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attr  string `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Attr) Reset() {
	*x = Attr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attr) ProtoMessage() {}

func (x *Attr) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attr.ProtoReflect.Descriptor instead.
func (*Attr) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{2}
}

func (x *Attr) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

func (x *Attr) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseId int64 `protobuf:"varint,1,opt,name=baseId,proto3" json:"baseId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *AddEquipmentRequest) Reset() {
	*x = AddEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEquipmentRequest) ProtoMessage() {}

func (x *AddEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEquipmentRequest.ProtoReflect.Descriptor instead.
func (*AddEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{3}
}

func (x *AddEquipmentRequest) GetBaseId() int64 {
	if x != nil {
		return x.BaseId
	}
	return 0
}

func (x *AddEquipmentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 正常返回值, 其他的值为错误码
	Message string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *AddEquipmentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddEquipmentResponse) Reset() {
	*x = AddEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEquipmentResponse) ProtoMessage() {}

func (x *AddEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEquipmentResponse.ProtoReflect.Descriptor instead.
func (*AddEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{4}
}

func (x *AddEquipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddEquipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddEquipmentResponse) GetData() *AddEquipmentResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpgradeEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpgradeEquipmentRequest) Reset() {
	*x = UpgradeEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradeEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeEquipmentRequest) ProtoMessage() {}

func (x *UpgradeEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeEquipmentRequest.ProtoReflect.Descriptor instead.
func (*UpgradeEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{5}
}

func (x *UpgradeEquipmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpgradeEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 正常返回值, 其他的值为错误码
	Message string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *UpgradeEquipmentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpgradeEquipmentResponse) Reset() {
	*x = UpgradeEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradeEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeEquipmentResponse) ProtoMessage() {}

func (x *UpgradeEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeEquipmentResponse.ProtoReflect.Descriptor instead.
func (*UpgradeEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{6}
}

func (x *UpgradeEquipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpgradeEquipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpgradeEquipmentResponse) GetData() *UpgradeEquipmentResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddFightEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position   int32 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	UserHeroId int64 `protobuf:"varint,3,opt,name=userHeroId,proto3" json:"userHeroId,omitempty"`
}

func (x *AddFightEquipmentRequest) Reset() {
	*x = AddFightEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFightEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFightEquipmentRequest) ProtoMessage() {}

func (x *AddFightEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFightEquipmentRequest.ProtoReflect.Descriptor instead.
func (*AddFightEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{7}
}

func (x *AddFightEquipmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddFightEquipmentRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *AddFightEquipmentRequest) GetUserHeroId() int64 {
	if x != nil {
		return x.UserHeroId
	}
	return 0
}

type AddFightEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 正常返回值, 其他的值为错误码
	Message string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *AddFightEquipmentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddFightEquipmentResponse) Reset() {
	*x = AddFightEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFightEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFightEquipmentResponse) ProtoMessage() {}

func (x *AddFightEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFightEquipmentResponse.ProtoReflect.Descriptor instead.
func (*AddFightEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{8}
}

func (x *AddFightEquipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddFightEquipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddFightEquipmentResponse) GetData() *AddFightEquipmentResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClearFightEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClearFightEquipmentRequest) Reset() {
	*x = ClearFightEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearFightEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearFightEquipmentRequest) ProtoMessage() {}

func (x *ClearFightEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearFightEquipmentRequest.ProtoReflect.Descriptor instead.
func (*ClearFightEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{9}
}

func (x *ClearFightEquipmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClearFightEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 正常返回值, 其他的值为错误码
	Message string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *ClearFightEquipmentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClearFightEquipmentResponse) Reset() {
	*x = ClearFightEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearFightEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearFightEquipmentResponse) ProtoMessage() {}

func (x *ClearFightEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearFightEquipmentResponse.ProtoReflect.Descriptor instead.
func (*ClearFightEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{10}
}

func (x *ClearFightEquipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClearFightEquipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClearFightEquipmentResponse) GetData() *ClearFightEquipmentResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ListEquipmentRequest) Reset() {
	*x = ListEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEquipmentRequest) ProtoMessage() {}

func (x *ListEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEquipmentRequest.ProtoReflect.Descriptor instead.
func (*ListEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{11}
}

func (x *ListEquipmentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 正常返回值, 其他的值为错误码
	Message string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *ListEquipmentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ListEquipmentResponse) Reset() {
	*x = ListEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEquipmentResponse) ProtoMessage() {}

func (x *ListEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEquipmentResponse.ProtoReflect.Descriptor instead.
func (*ListEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{12}
}

func (x *ListEquipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListEquipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListEquipmentResponse) GetData() *ListEquipmentResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListHeroEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserHeroId int64  `protobuf:"varint,1,opt,name=userHeroId,proto3" json:"userHeroId,omitempty"`
	GameId     int64  `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`    // 游戏id
	Universe   string `protobuf:"bytes,3,opt,name=universe,proto3" json:"universe,omitempty"` // 宇宙类型
}

func (x *ListHeroEquipmentRequest) Reset() {
	*x = ListHeroEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHeroEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroEquipmentRequest) ProtoMessage() {}

func (x *ListHeroEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroEquipmentRequest.ProtoReflect.Descriptor instead.
func (*ListHeroEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{13}
}

func (x *ListHeroEquipmentRequest) GetUserHeroId() int64 {
	if x != nil {
		return x.UserHeroId
	}
	return 0
}

func (x *ListHeroEquipmentRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ListHeroEquipmentRequest) GetUniverse() string {
	if x != nil {
		return x.Universe
	}
	return ""
}

type ListHeroEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 正常返回值, 其他的值为错误码
	Message string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *ListHeroEquipmentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ListHeroEquipmentResponse) Reset() {
	*x = ListHeroEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHeroEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroEquipmentResponse) ProtoMessage() {}

func (x *ListHeroEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroEquipmentResponse.ProtoReflect.Descriptor instead.
func (*ListHeroEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{14}
}

func (x *ListHeroEquipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListHeroEquipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListHeroEquipmentResponse) GetData() *ListHeroEquipmentResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchHeroEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserHeroId []int64 `protobuf:"varint,1,rep,packed,name=userHeroId,proto3" json:"userHeroId,omitempty"`
	GameId     int64   `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`    // 游戏id
	Universe   string  `protobuf:"bytes,3,opt,name=universe,proto3" json:"universe,omitempty"` // 宇宙类型
}

func (x *BatchHeroEquipmentRequest) Reset() {
	*x = BatchHeroEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchHeroEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchHeroEquipmentRequest) ProtoMessage() {}

func (x *BatchHeroEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchHeroEquipmentRequest.ProtoReflect.Descriptor instead.
func (*BatchHeroEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{15}
}

func (x *BatchHeroEquipmentRequest) GetUserHeroId() []int64 {
	if x != nil {
		return x.UserHeroId
	}
	return nil
}

func (x *BatchHeroEquipmentRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *BatchHeroEquipmentRequest) GetUniverse() string {
	if x != nil {
		return x.Universe
	}
	return ""
}

type BatchHeroEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 正常返回值, 其他的值为错误码
	Message string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *BatchHeroEquipmentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BatchHeroEquipmentResponse) Reset() {
	*x = BatchHeroEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchHeroEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchHeroEquipmentResponse) ProtoMessage() {}

func (x *BatchHeroEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchHeroEquipmentResponse.ProtoReflect.Descriptor instead.
func (*BatchHeroEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{16}
}

func (x *BatchHeroEquipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchHeroEquipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchHeroEquipmentResponse) GetData() *BatchHeroEquipmentResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type BreakDownEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BreakDownEquipmentRequest) Reset() {
	*x = BreakDownEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreakDownEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakDownEquipmentRequest) ProtoMessage() {}

func (x *BreakDownEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakDownEquipmentRequest.ProtoReflect.Descriptor instead.
func (*BreakDownEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{17}
}

func (x *BreakDownEquipmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BreakDownEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 正常返回值, 其他的值为错误码
	Message string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *BreakDownEquipmentResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BreakDownEquipmentResponse) Reset() {
	*x = BreakDownEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreakDownEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakDownEquipmentResponse) ProtoMessage() {}

func (x *BreakDownEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakDownEquipmentResponse.ProtoReflect.Descriptor instead.
func (*BreakDownEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{18}
}

func (x *BreakDownEquipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BreakDownEquipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BreakDownEquipmentResponse) GetData() *BreakDownEquipmentResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddEquipmentResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 通知结果
}

func (x *AddEquipmentResponse_Data) Reset() {
	*x = AddEquipmentResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEquipmentResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEquipmentResponse_Data) ProtoMessage() {}

func (x *AddEquipmentResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEquipmentResponse_Data.ProtoReflect.Descriptor instead.
func (*AddEquipmentResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AddEquipmentResponse_Data) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpgradeEquipmentResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level     int32   `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Success   bool    `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`    // 升级结果
	AddValues []*Attr `protobuf:"bytes,4,rep,name=addValues,proto3" json:"addValues,omitempty"` //增加值
}

func (x *UpgradeEquipmentResponse_Data) Reset() {
	*x = UpgradeEquipmentResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradeEquipmentResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeEquipmentResponse_Data) ProtoMessage() {}

func (x *UpgradeEquipmentResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeEquipmentResponse_Data.ProtoReflect.Descriptor instead.
func (*UpgradeEquipmentResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpgradeEquipmentResponse_Data) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpgradeEquipmentResponse_Data) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpgradeEquipmentResponse_Data) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpgradeEquipmentResponse_Data) GetAddValues() []*Attr {
	if x != nil {
		return x.AddValues
	}
	return nil
}

type AddFightEquipmentResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 通知结果
}

func (x *AddFightEquipmentResponse_Data) Reset() {
	*x = AddFightEquipmentResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFightEquipmentResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFightEquipmentResponse_Data) ProtoMessage() {}

func (x *AddFightEquipmentResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFightEquipmentResponse_Data.ProtoReflect.Descriptor instead.
func (*AddFightEquipmentResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{8, 0}
}

func (x *AddFightEquipmentResponse_Data) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ClearFightEquipmentResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 通知结果
}

func (x *ClearFightEquipmentResponse_Data) Reset() {
	*x = ClearFightEquipmentResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearFightEquipmentResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearFightEquipmentResponse_Data) ProtoMessage() {}

func (x *ClearFightEquipmentResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearFightEquipmentResponse_Data.ProtoReflect.Descriptor instead.
func (*ClearFightEquipmentResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ClearFightEquipmentResponse_Data) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListEquipmentResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equipments []*EquipmentInfo `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty"`
}

func (x *ListEquipmentResponse_Data) Reset() {
	*x = ListEquipmentResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEquipmentResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEquipmentResponse_Data) ProtoMessage() {}

func (x *ListEquipmentResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEquipmentResponse_Data.ProtoReflect.Descriptor instead.
func (*ListEquipmentResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{12, 0}
}

func (x *ListEquipmentResponse_Data) GetEquipments() []*EquipmentInfo {
	if x != nil {
		return x.Equipments
	}
	return nil
}

type ListHeroEquipmentResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroEquipment *HeroEquipment `protobuf:"bytes,1,opt,name=heroEquipment,proto3" json:"heroEquipment,omitempty"`
}

func (x *ListHeroEquipmentResponse_Data) Reset() {
	*x = ListHeroEquipmentResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHeroEquipmentResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroEquipmentResponse_Data) ProtoMessage() {}

func (x *ListHeroEquipmentResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroEquipmentResponse_Data.ProtoReflect.Descriptor instead.
func (*ListHeroEquipmentResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{14, 0}
}

func (x *ListHeroEquipmentResponse_Data) GetHeroEquipment() *HeroEquipment {
	if x != nil {
		return x.HeroEquipment
	}
	return nil
}

type BatchHeroEquipmentResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchHeroEquipments []*HeroEquipment `protobuf:"bytes,1,rep,name=batchHeroEquipments,proto3" json:"batchHeroEquipments,omitempty"`
}

func (x *BatchHeroEquipmentResponse_Data) Reset() {
	*x = BatchHeroEquipmentResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchHeroEquipmentResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchHeroEquipmentResponse_Data) ProtoMessage() {}

func (x *BatchHeroEquipmentResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchHeroEquipmentResponse_Data.ProtoReflect.Descriptor instead.
func (*BatchHeroEquipmentResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{16, 0}
}

func (x *BatchHeroEquipmentResponse_Data) GetBatchHeroEquipments() []*HeroEquipment {
	if x != nil {
		return x.BatchHeroEquipments
	}
	return nil
}

type BreakDownEquipmentResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 分解结果
}

func (x *BreakDownEquipmentResponse_Data) Reset() {
	*x = BreakDownEquipmentResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_in_v1_vo_equipment_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreakDownEquipmentResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakDownEquipmentResponse_Data) ProtoMessage() {}

func (x *BreakDownEquipmentResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_in_v1_vo_equipment_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakDownEquipmentResponse_Data.ProtoReflect.Descriptor instead.
func (*BreakDownEquipmentResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_in_v1_vo_equipment_proto_rawDescGZIP(), []int{18, 0}
}

func (x *BreakDownEquipmentResponse_Data) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_in_v1_vo_equipment_proto protoreflect.FileDescriptor

var file_api_in_v1_vo_equipment_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x6f, 0x2f, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x98, 0x01, 0x0a, 0x0d, 0x48, 0x65,
	0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x0a, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x74,
	0x74, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x41, 0x74, 0x74, 0x72, 0x22, 0xe5, 0x02, 0x0a, 0x0d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x65, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x09,
	0x69, 0x6e, 0x69, 0x74, 0x41, 0x74, 0x74, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x52, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x33, 0x0a, 0x0c, 0x75,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74,
	0x74, 0x72, 0x52, 0x0c, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x04,
	0x41, 0x74, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x45,
	0x0a, 0x13, 0x41, 0x64, 0x64, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x20, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x29, 0x0a, 0x17, 0x55, 0x70, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0xfd, 0x01, 0x0a, 0x18, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x75, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x52, 0x09, 0x61, 0x64, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x66, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x46, 0x69, 0x67, 0x68, 0x74, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x22, 0xaa, 0x01, 0x0a, 0x19,
	0x41, 0x64, 0x64, 0x46, 0x69, 0x67, 0x68, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x69, 0x67, 0x68, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x20, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2c, 0x0a, 0x1a, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x46, 0x69, 0x67, 0x68, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xae, 0x01, 0x0a, 0x1b, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x46, 0x69, 0x67, 0x68, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x46, 0x69, 0x67, 0x68, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x20, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xc2, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x39, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x40, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x38, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x6e, 0x0a, 0x18,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x73,
	0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x22, 0xd0, 0x01, 0x0a,
	0x19, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x46, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x3e, 0x0a, 0x0d, 0x68, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0d, 0x68, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x6f, 0x0a, 0x19, 0x42, 0x61, 0x74, 0x63, 0x68, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x22, 0xde, 0x01, 0x0a, 0x1a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x48, 0x65, 0x72,
	0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x52, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x4a, 0x0a, 0x13, 0x62, 0x61, 0x74, 0x63, 0x68, 0x48, 0x65,
	0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x13, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x2b, 0x0a, 0x19, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xac,
	0x01, 0x0a, 0x1a, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x20, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0x5f, 0x0a,
	0x0f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x71, 0x75, 0x69, 0x70, 0x70,
	0x65, 0x64, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x03,
	0x12, 0x0d, 0x0a, 0x09, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6e, 0x10, 0x04, 0x12,
	0x0d, 0x0a, 0x09, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x05, 0x42, 0x22,
	0x5a, 0x20, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x69, 0x5f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x6f, 0x3b,
	0x76, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_in_v1_vo_equipment_proto_rawDescOnce sync.Once
	file_api_in_v1_vo_equipment_proto_rawDescData = file_api_in_v1_vo_equipment_proto_rawDesc
)

func file_api_in_v1_vo_equipment_proto_rawDescGZIP() []byte {
	file_api_in_v1_vo_equipment_proto_rawDescOnce.Do(func() {
		file_api_in_v1_vo_equipment_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_in_v1_vo_equipment_proto_rawDescData)
	})
	return file_api_in_v1_vo_equipment_proto_rawDescData
}

var file_api_in_v1_vo_equipment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_in_v1_vo_equipment_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_in_v1_vo_equipment_proto_goTypes = []interface{}{
	(EquipmentStatus)(0),                     // 0: api.in.v1.EquipmentStatus
	(*HeroEquipment)(nil),                    // 1: api.in.v1.HeroEquipment
	(*EquipmentInfo)(nil),                    // 2: api.in.v1.EquipmentInfo
	(*Attr)(nil),                             // 3: api.in.v1.Attr
	(*AddEquipmentRequest)(nil),              // 4: api.in.v1.AddEquipmentRequest
	(*AddEquipmentResponse)(nil),             // 5: api.in.v1.AddEquipmentResponse
	(*UpgradeEquipmentRequest)(nil),          // 6: api.in.v1.UpgradeEquipmentRequest
	(*UpgradeEquipmentResponse)(nil),         // 7: api.in.v1.UpgradeEquipmentResponse
	(*AddFightEquipmentRequest)(nil),         // 8: api.in.v1.AddFightEquipmentRequest
	(*AddFightEquipmentResponse)(nil),        // 9: api.in.v1.AddFightEquipmentResponse
	(*ClearFightEquipmentRequest)(nil),       // 10: api.in.v1.ClearFightEquipmentRequest
	(*ClearFightEquipmentResponse)(nil),      // 11: api.in.v1.ClearFightEquipmentResponse
	(*ListEquipmentRequest)(nil),             // 12: api.in.v1.ListEquipmentRequest
	(*ListEquipmentResponse)(nil),            // 13: api.in.v1.ListEquipmentResponse
	(*ListHeroEquipmentRequest)(nil),         // 14: api.in.v1.ListHeroEquipmentRequest
	(*ListHeroEquipmentResponse)(nil),        // 15: api.in.v1.ListHeroEquipmentResponse
	(*BatchHeroEquipmentRequest)(nil),        // 16: api.in.v1.BatchHeroEquipmentRequest
	(*BatchHeroEquipmentResponse)(nil),       // 17: api.in.v1.BatchHeroEquipmentResponse
	(*BreakDownEquipmentRequest)(nil),        // 18: api.in.v1.BreakDownEquipmentRequest
	(*BreakDownEquipmentResponse)(nil),       // 19: api.in.v1.BreakDownEquipmentResponse
	(*AddEquipmentResponse_Data)(nil),        // 20: api.in.v1.AddEquipmentResponse.Data
	(*UpgradeEquipmentResponse_Data)(nil),    // 21: api.in.v1.UpgradeEquipmentResponse.Data
	(*AddFightEquipmentResponse_Data)(nil),   // 22: api.in.v1.AddFightEquipmentResponse.Data
	(*ClearFightEquipmentResponse_Data)(nil), // 23: api.in.v1.ClearFightEquipmentResponse.Data
	(*ListEquipmentResponse_Data)(nil),       // 24: api.in.v1.ListEquipmentResponse.Data
	(*ListHeroEquipmentResponse_Data)(nil),   // 25: api.in.v1.ListHeroEquipmentResponse.Data
	(*BatchHeroEquipmentResponse_Data)(nil),  // 26: api.in.v1.BatchHeroEquipmentResponse.Data
	(*BreakDownEquipmentResponse_Data)(nil),  // 27: api.in.v1.BreakDownEquipmentResponse.Data
}
var file_api_in_v1_vo_equipment_proto_depIdxs = []int32{
	2,  // 0: api.in.v1.HeroEquipment.equipments:type_name -> api.in.v1.EquipmentInfo
	3,  // 1: api.in.v1.HeroEquipment.totalAttr:type_name -> api.in.v1.Attr
	0,  // 2: api.in.v1.EquipmentInfo.status:type_name -> api.in.v1.EquipmentStatus
	3,  // 3: api.in.v1.EquipmentInfo.initAttrs:type_name -> api.in.v1.Attr
	3,  // 4: api.in.v1.EquipmentInfo.upgradeAttrs:type_name -> api.in.v1.Attr
	20, // 5: api.in.v1.AddEquipmentResponse.data:type_name -> api.in.v1.AddEquipmentResponse.Data
	21, // 6: api.in.v1.UpgradeEquipmentResponse.data:type_name -> api.in.v1.UpgradeEquipmentResponse.Data
	22, // 7: api.in.v1.AddFightEquipmentResponse.data:type_name -> api.in.v1.AddFightEquipmentResponse.Data
	23, // 8: api.in.v1.ClearFightEquipmentResponse.data:type_name -> api.in.v1.ClearFightEquipmentResponse.Data
	24, // 9: api.in.v1.ListEquipmentResponse.data:type_name -> api.in.v1.ListEquipmentResponse.Data
	25, // 10: api.in.v1.ListHeroEquipmentResponse.data:type_name -> api.in.v1.ListHeroEquipmentResponse.Data
	26, // 11: api.in.v1.BatchHeroEquipmentResponse.data:type_name -> api.in.v1.BatchHeroEquipmentResponse.Data
	27, // 12: api.in.v1.BreakDownEquipmentResponse.data:type_name -> api.in.v1.BreakDownEquipmentResponse.Data
	3,  // 13: api.in.v1.UpgradeEquipmentResponse.Data.addValues:type_name -> api.in.v1.Attr
	2,  // 14: api.in.v1.ListEquipmentResponse.Data.equipments:type_name -> api.in.v1.EquipmentInfo
	1,  // 15: api.in.v1.ListHeroEquipmentResponse.Data.heroEquipment:type_name -> api.in.v1.HeroEquipment
	1,  // 16: api.in.v1.BatchHeroEquipmentResponse.Data.batchHeroEquipments:type_name -> api.in.v1.HeroEquipment
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_in_v1_vo_equipment_proto_init() }
func file_api_in_v1_vo_equipment_proto_init() {
	if File_api_in_v1_vo_equipment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_in_v1_vo_equipment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroEquipment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradeEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradeEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFightEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFightEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearFightEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearFightEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHeroEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHeroEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchHeroEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchHeroEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreakDownEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreakDownEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEquipmentResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradeEquipmentResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFightEquipmentResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearFightEquipmentResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEquipmentResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHeroEquipmentResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchHeroEquipmentResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_in_v1_vo_equipment_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreakDownEquipmentResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_in_v1_vo_equipment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_in_v1_vo_equipment_proto_goTypes,
		DependencyIndexes: file_api_in_v1_vo_equipment_proto_depIdxs,
		EnumInfos:         file_api_in_v1_vo_equipment_proto_enumTypes,
		MessageInfos:      file_api_in_v1_vo_equipment_proto_msgTypes,
	}.Build()
	File_api_in_v1_vo_equipment_proto = out.File
	file_api_in_v1_vo_equipment_proto_rawDesc = nil
	file_api_in_v1_vo_equipment_proto_goTypes = nil
	file_api_in_v1_vo_equipment_proto_depIdxs = nil
}
